services:

  # ─── FastAPI Application ──────────────────────────────────
  app:
    build: .                          # build dari Dockerfile di folder ini
    container_name: creditrisk_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env                          # baca semua env vars dari .env
    environment:
      # Override database URL untuk pakai nama container, bukan localhost
      # Di dalam Docker network, container komunikasi pakai nama container
      # bukan "localhost" — karena setiap container punya "localhost" sendiri!
      DATABASE_URL: postgresql://creditrisk:creditrisk123@postgres:5432/creditrisk_db
      ASYNC_DATABASE_URL: postgresql+asyncpg://creditrisk:creditrisk123@postgres:5432/creditrisk_db
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    volumes:
      # Mount folder data supaya model dan ChromaDB persist
      - ./data/models:/app/data/models
      - ./data/policy_docs:/app/data/policy_docs
      - chroma_data:/app/data/chroma_db
      - mlflow_data:/app/data/mlflow
    depends_on:
      postgres:
        condition: service_healthy   # tunggu sampai postgres benar-benar siap
      redis:
        condition: service_healthy

  # ─── PostgreSQL ───────────────────────────────────────────
  postgres:
    image: postgres:16-alpine
    container_name: creditrisk_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: creditrisk
      POSTGRES_PASSWORD: creditrisk123
      POSTGRES_DB: creditrisk_db
      POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U creditrisk -d creditrisk_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ─── Redis ────────────────────────────────────────────────
  redis:
    image: redis:7-alpine
    container_name: creditrisk_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  chroma_data:
  mlflow_data: